Animals/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Animals.Models;
using AutoMapper;
using BusinessLayer;
using BusinessLayer.Managers;
using BusinessLayer.Models;
using DataAccessLayer.Models;
using Microsoft.AspNet.Identity.Owin;

namespace Animals.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly AnimalsManager _animalsManager;
        private readonly HomesManager _homesManager;
        private readonly Mapper _mapper;

        public AnimalsController()
        {
            _animalsManager = new AnimalsManager();
            _homesManager = new HomesManager();

            var conf = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<AnimalModel, AnimalViewModel>();
                cfg.CreateMap<HomeModel, HomeViewModel>();

                cfg.CreateMap<AnimalViewModel, AnimalModel>();
                cfg.CreateMap<HomeViewModel, HomeModel>();
            });

            _mapper = new Mapper(conf);
        }

        public ActionResult Index()
        {
            var animals = _animalsManager.GetAllAnimals();
            var animalsMap = _mapper.Map<IList<AnimalViewModel>>(animals);
            var result = new GetAllAnimalViewModel {Animals = animalsMap, Lang = GetLang() };
            return View(result);
        }

        public ActionResult Homes()
        {
            var homes = _homesManager.GetAllHomes();
            var homesMap = _mapper.Map<IList<HomeViewModel>>(homes);
            var result = new GetAllHomeViewModel {Homes = homesMap, Lang = GetLang() };
            return View(result);
        }

        public string GetLang()
        {
            var user = HttpContext.User.Identity as ClaimsIdentity;
            if (user != null)
            {
                var claimLang = user.Claims.FirstOrDefault(x => x.Type == "Lang");
                return claimLang != null ? claimLang.Value : "";
            }

            return "";
        }
    }
}

Animals/Controllers/SpaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Animals.Controllers
{
    public class SpaController : Controller
    {
        // GET: Spa
        public ActionResult Index()
        {
            return View();
        }
    }
}

Animals/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Animals", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Animals", "Index", "Animals")</li>
                    <li>@Html.ActionLink("Homes", "Homes", "Animals")</li>
                    <li>@Html.ActionLink("SPA", "Index", "Spa")</li>
                    <li></li>
                    <li></li>
                    <li></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Registration", "Index", "Account")</li>
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }
                    else
                    {
                        <li><a href="#" id="sign-out">SingOut</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2020 - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/Controller/Account/index.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>